frontend:
  image:
    repository: ghcr.io/infonl/podiumd-office-plugin-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 3000

backend:
  image:
    repository: ghcr.io/infonl/podiumd-office-plugin-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 3003
