frontend:
  image:
    repository: ghcr.io/infonl/podiumd-office-add-in-frontend
    tag: v0.0.146@sha256:d9ae57431de55b75923819cef83438f40ad73a7ab6e4deb8034f5d9c9b7e2a10
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  # -- The frontend URL where the manifest.xml and static js file are served
  frontendUrl: "https://localhost:3000"

backend:
  image:
    repository: ghcr.io/infonl/podiumd-office-add-in-backend
    tag: v0.0.140@sha256:5673621b5ecc7612115141cd55acb8542625adf818192f2cb5199342c702fbff
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3003
  # -- Secret key used for generating and validating JWT tokens for secure communication
  jwtSecret: "SECRECT_KEY_PLACEHOLDER"
  # -- Base URL to the openzaak API
  apiBaseUrl: "http://localhost:8020"

  certificate:
    # -- path to ca certificate file. If not specified, a self signed certificate will be generated for localhost
    caPath: ""
    # -- path to private key file. If not specified, a self signed certificate will be generated for localhost
    keyPath: ""
    # -- path to certificate file. If not specified, a self signed certificate will be generated for localhost
    certPath: ""
