frontend:
  image:
    repository: ghcr.io/infonl/podiumd-office-add-in-frontend
    tag: v0.0.129@sha256:a1d91c536f45fcac1c0b002ec373ca65f777bd0622cd340b962e3bbbf102983a
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  # -- The frontend URL where the manifest.xml and static js file are served
  frontendUrl: "https://localhost:3000"

backend:
  image:
    repository: ghcr.io/infonl/podiumd-office-add-in-backend
    tag: v0.0.140@sha256:5673621b5ecc7612115141cd55acb8542625adf818192f2cb5199342c702fbff
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3003
  # -- Secret key used for generating and validating JWT tokens for secure communication
  jwtSecret: "SECRECT_KEY_PLACEHOLDER"
  # -- Base URL to the openzaak API
  apiBaseUrl: "http://localhost:8020"

  certificate:
    # -- path to ca certificate file. If not specified, a self signed certificate will be generated for localhost
    caPath: ""
    # -- path to private key file. If not specified, a self signed certificate will be generated for localhost
    keyPath: ""
    # -- path to certificate file. If not specified, a self signed certificate will be generated for localhost
    certPath: ""
