frontend:
  image:
    repository: ghcr.io/infonl/podiumd-office-add-in-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  # -- The frontend URL where the manifest.xml and static js file are served
  frontendUrl: "https://localhost:3000"

backend:
  image:
    repository: ghcr.io/infonl/podiumd-office-add-in-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3003
  # -- Secret key used for generating and validating JWT tokens for secure communication
  jwtSecret: "SECRECT_KEY_PLACEHOLDER"
  # -- Base URL to the openzaak API
  apiBaseUrl: "http://localhost:8020"
