frontend:
  image:
    repository: ghcr.io/infonl/podiumd-office-add-in-frontend
    tag: v0.0.112@sha256:0848fd11077675325524658a1f5c0f66022c4d521fc57095c38f5fe854460c6a
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  # -- The frontend URL where the manifest.xml and static js file are served
  frontendUrl: "https://localhost:3000"

backend:
  image:
    repository: ghcr.io/infonl/podiumd-office-add-in-backend
    tag: v0.0.129@sha256:902aea02051026ad9188c7380c1bc98161dcb078cddeb0035baf914a370bfd94
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3003
  # -- Secret key used for generating and validating JWT tokens for secure communication
  jwtSecret: "SECRECT_KEY_PLACEHOLDER"
  # -- Base URL to the openzaak API
  apiBaseUrl: "http://localhost:8020"

  certificate:
    # -- path to ca certificate file. If not specified, a self signed certificate will be generated for localhost
    caPath: ""
    # -- path to private key file. If not specified, a self signed certificate will be generated for localhost
    keyPath: ""
    # -- path to certificate file. If not specified, a self signed certificate will be generated for localhost
    certPath: ""
