apiVersion: v1
kind: Service
metadata:
  name: {{ include "office-add-in.backend.fullname" . }}
  labels:
    {{- include "office-add-in.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "office-add-in.backend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 3003
