apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-add-in-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: office-add-in-backend
  template:
    metadata:
      labels:
        app: office-add-in-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.backend.image.pullPolicy }}"
          ports:
            - containerPort: 3003
          env:
            - name: JWT_SECRET
              value: {{ .Values.backend.jwtSecret | quote }}
            - name: API_BASE_URL
              value: {{ .Values.backend.apiBaseUrl | quote }}
            - name: CA_CERT_PATH
              value: {{ .Values.backend.certificate.caPath | default "./ca-cert.pem" | quote }}
            - name: KEY_PATH
              value: {{ .Values.backend.certificate.keyPath | default "./key.pem" | quote }}
            - name: CERT_PATH
              value: {{ .Values.backend.certificate.certPath | default "./cert.pem" | quote }}
            - name: GENERATE_SELF_SIGNED
              value: {{- if .Values.backend.certificate.certPath }}"false"{{- else }}"true" {{- end }}
