apiVersion: v1
kind: Service
metadata:
  name: {{ include "office-add-in.backend.fullname" . }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: office-add-in-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 3003
