apiVersion: v1
kind: Service
metadata:
  name: {{ include "office-add-in.frontend.fullname" . }}
  labels:
    {{- include "office-add-in.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "office-add-in.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
