apiVersion: v1
kind: Service
metadata:
  name: office-add-in-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: office-add-in-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
