# SPDX-FileCopyrightText: 2025 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+

name: Build and Release Office Plugin

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: '.nvmrc'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build

    - name: Package Artifacts
      run: |
        mkdir -p release
        cp -r office-add-in/dist release/

    - name: Archive Artifacts
      #if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: office-plugin-artifacts
        path: release/

  next-version:
    runs-on: ubuntu-24.04
    outputs:
      old-version: ${{ github.ref == 'refs/heads/main' && steps.get-tag-main.outputs.old_tag || steps.get-tag-non-main.outputs.old_tag }}
      version: ${{ github.ref == 'refs/heads/main' && steps.get-tag-main.outputs.new_tag || steps.get-tag-non-main.outputs.new_tag }}
    steps:
    # Checkout the repository including tags
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    # Determine the next semantic version based on the commit message tags
    - name: Get next tag on main
      id: get-tag-main
      if: ${{ github.ref == 'refs/heads/main'}}
      uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c # 1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PRERELEASE: false
        DEFAULT_BUMP: patch
        WITH_V: true
        RELEASE_BRANCHES: main
    # If not on main, Determine the next semantic version based on the commit message tags without pushing tags`
    - name: Get next tag on non-main
      id: get-tag-non-main
      if: ${{ github.ref != 'refs/heads/main'}}
      uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c # 1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PRERELEASE: false
        DEFAULT_BUMP: patch
        WITH_V: true
        RELEASE_BRANCHES: main
        DRY_RUN: true
    - name: Print new version
      run: |
        echo "Next version: ${{ github.ref == 'refs/heads/main' && steps.get-tag-main.outputs.new_tag || steps.get-tag-non-main.outputs.new_tag }}"

  create-release:
    needs: [build,next-version]
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Download office-plugin-artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: office-plugin-artifacts
        path: release-${{ needs.next-version.outputs.version }}/ 

    - name: Create zip
      run: |
        zip -r podiumd-office-plugin-${{ needs.next-version.outputs.version }}.zip release-${{ needs.next-version.outputs.version }}

    - name: Create Github release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ needs.next-version.outputs.version }} podiumd-office-plugin-${{ needs.next-version.outputs.version }}.zip --notes-start-tag ${{ needs.next-version.outputs.old-version }}

  create-docker-image:
    needs: [build,next-version,create-release] # no release, no docker image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
      with:
        context: ./office-add-in
        push: true
        tags: |
          ghcr.io/podiumd-office-add-in-frontend:latest
          ghcr.io/podiumd-office-add-in-frontend:${{ needs.next-version.outputs.version }}

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
      with:
        context: ./office-backend
        push: true
        tags: |
          ghcr.io/podiumd-office-add-in-backend:latest
          ghcr.io/podiumd-office-add-in-backend:${{ needs.next-version.outputs.version }}
