# SPDX-FileCopyrightText: 2025 Info
# SPDX-License-Identifier: EUPL-1.2+

name: Build and Release Office Plugin

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Node.js
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version-file: '.nvmrc'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build

    - name: Package Artifacts
      run: |
        mkdir -p release
        cp -r office-add-in/dist release/

    - name: Archive Artifacts
      #if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: office-plugin-artifacts
        path: release/

  next-version:
    runs-on: ubuntu-24.04
    outputs:
      old-version: ${{ github.ref == 'refs/heads/main' && steps.get-tag-main.outputs.old_tag || steps.get-tag-non-main.outputs.old_tag }}
      version: ${{ github.ref == 'refs/heads/main' && steps.get-tag-main.outputs.new_tag || steps.get-tag-non-main.outputs.new_tag }}
    steps:
    # Checkout the repository including tags
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    # Determine the next semantic version based on the commit message tags
    - name: Get next tag on main
      id: get-tag-main
      if: ${{ github.ref == 'refs/heads/main'}}
      uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297 # 1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PRERELEASE: false
        DEFAULT_BUMP: patch
        WITH_V: true
        RELEASE_BRANCHES: main
    # If not on main, Determine the next semantic version based on the commit message tags without pushing tags`
    - name: Get next tag on non-main
      id: get-tag-non-main
      if: ${{ github.ref != 'refs/heads/main'}}
      uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297 # 1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PRERELEASE: false
        DEFAULT_BUMP: patch
        WITH_V: true
        RELEASE_BRANCHES: main
        DRY_RUN: true
    - name: Print new version
      run: |
        echo "Next version: ${{ github.ref == 'refs/heads/main' && steps.get-tag-main.outputs.new_tag || steps.get-tag-non-main.outputs.new_tag }}"

  release:
    needs: [build,next-version]
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:

    - name: Download office-plugin-artifacts
      uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
      with:
        name: office-plugin-artifacts
        path: release-${{ needs.next-version.outputs.version }}/ 

    - name: Create zip
      run: |
        zip -r podiumd-office-plugin-${{ needs.next-version.outputs.version }}.zip release-${{ needs.next-version.outputs.version }}

    - name: Create Github release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ needs.next-version.outputs.version }} podiumd-office-plugin-${{ needs.next-version.outputs.version }}.zip --notes-start-tag ${{ needs.next-version.outputs.old-version }}
